name: Vars and secrets
on: [push, pull_request, issues, workflow_dispatch]

jobs:
    Configuration-variables:
        runs-on: ${{ vars.JOBS_RUNNER }}
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            