name: Repository Events
on: 
    push:
    pull_request:
        types: [opened, assigned, reopened, synchronize]
    issues:
        types: [opened]

jobs:
    events:
        runs-on: ubuntu-latest
        steps:
            - name: commands run
              run: | 
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4
              
