name: First workflow
on: [push]

jobs: 
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hi"
            - name: Multiline command
              run: |
                node -v
                npm -v
    parallel-job-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: View OS Version
              run: cat /etc/os-release
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a string
              run: Write-Output "Windows string"
            - name: Error step
              run: Does not exist
