name: Matrix
on: [push]

jobs:
    node-matrix:
        strategy: 
            matrix:
                os: [ubuntu-latest, windows-latest] 
                node-version: [14,15,16,18,20]
                include:
                    - os: ubuntu-latest
                      is-ubuntu: true
                exclude:
                    - os: ubuntu-latest
                      node-version: 16
            # max-parallel: 3
        runs-on: ${{ matrix.os }}
        
        steps:
            - run: node -v
            - run: echo '${{ toJson(matrix)}}'
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version}}
            - run: node -v

