name: Status check 
on: [push, pull_request, issues, workflow_dispatch,]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step-1
              run: sleep 90
              timeout-minutes: 1
            - name: Step-2
              id: step-2
              continue-on-error: true
              run: exit 1
            - name: Runs on step2 faliure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo 'Step 2 has failed'
              # run: echo "Runs only on failure"
            - name: Runs on faliure
              if: failure()
              run: echo "Runs only on failure"
            - name: Runs on success
              if: success()
              run: echo "Runs on success"
            - name: Always run
              if: always()
              run: echo "Always runs"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2'