name: Status check 
on: [push, pull_request, issues, workflow_dispatch,]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step-1
              run: sleep 20
            - name: Runs on faliure
              if: failure()
              run: echo "Runs only on failure"
            - name: Runs on success
              if: success()
              run: echo "Runs on success"
            - name: Always run
              if: always()
              run: echo "Always runs"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2'